[tool.poetry]
name = "confz"
version = "1.2.3"
description = "ConfZ is a configuration management library for Python based on pydantic."
license = "MIT"
authors = ["Zühlke"]
readme = "README.md"
homepage = "https://github.com/Zuehlke/ConfZ"
repository = "https://github.com/Zuehlke/ConfZ"
documentation = "https://confz.readthedocs.io"
keywords = ["Configuration Management", "Config Management"]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.9.0"
PyYAML = ">=5.4.1, <7.0.0"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
Sphinx = "^4.2.0"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.16.0"
black = {extras = ["d"], version = "^21.12b0"}
mypy = "^0.930"
pylint = "^2.12.2"

[tool.black]
# Use default black configuration

[tool.pylint.messages_control]
disable = [
    "wrong-hanging-indentation",    # to work together with black
    "bad-whitespace"                # to work together with black
]

[tool.pylint.format]
max-line-length = "88"              # to work together with black

[tool.mypy]
# Use default mypy configuration

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
